# Generated by Django 5.2.6 on 2025-10-27 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código/Tag QR')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('fabricante', models.CharField(blank=True, max_length=200, verbose_name='Fabricante')),
                ('numero_serie', models.CharField(blank=True, max_length=200, verbose_name='Número de Série')),
                ('fornecedor', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor')),
                ('ambiente', models.CharField(default='Não informado', max_length=200, verbose_name='Ambiente/Localização')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Manutenção', 'Manutenção')], default='Ativo', max_length=20, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AtivoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de Movimentação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_movimentacoes', to='chamados.ativo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Histórico do Ativo',
                'verbose_name_plural': 'Históricos dos Ativos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.CharField(max_length=200, verbose_name='Ativo/Equipamento')),
                ('ambiente', models.CharField(default='Não informado', max_length=200, verbose_name='Ambiente')),
                ('urgencia', models.CharField(choices=[('Crítico', 'Crítico'), ('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], default='Média', max_length=20, verbose_name='Nível de Urgência')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('AGUARDANDO RESP', 'Aguardando Responsáveis'), ('EM ANDAMENTO', 'Em Andamento'), ('REALIZADO', 'Realizado'), ('CONCLUÍDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=30, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_sugerida', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('responsaveis', models.ManyToManyField(blank=True, related_name='chamados_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='chamados/anexos/%Y/%m/%d/')),
                ('nome_original', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
        migrations.CreateModel(
            name='ChamadoStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('descricao', models.TextField(verbose_name='Descrição da Mudança')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='chamados.chamado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoStatusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='chamados/historico/%Y/%m/%d/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='chamados.chamadostatushistory')),
            ],
            options={
                'verbose_name': 'Imagem do Histórico',
                'verbose_name_plural': 'Imagens do Histórico',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
