# Generated by Django 5.2.7 on 2025-10-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ativo', models.CharField(max_length=200)),
                ('ambiente', models.CharField(blank=True, max_length=100, null=True)),
                ('urgencia', models.CharField(max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
            ],
        ),
    ]
