# Generated by Django 5.2.7 on 2025-10-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='data_criacao',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='urgencia',
        ),
        migrations.AddField(
            model_name='chamado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('fechado', 'Fechado')], default='aberto', max_length=20),
        ),
    ]
