# Generated by Django 5.2.6 on 2025-10-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_sugerida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Sugerida'),
        ),
    ]
