# Generated by Django 5.2.7 on 2025-10-24 01:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_rename_data_criacao_chamado_criado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='chamado',
            name='ambiente',
            field=models.CharField(choices=[('producao', 'Produção'), ('homologacao', 'Homologação'), ('desenvolvimento', 'Desenvolvimento')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chamado',
            name='ativo',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chamado',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='chamados_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='urgencia',
            field=models.CharField(choices=[('critico', 'Crítico'), ('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='baixa', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamado',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('fechado', 'Fechado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='chamados.chamado')),
            ],
        ),
    ]
